# include ./kitty-themes/themes/OneDark.conf
# include ./TokioOneNightTheme.conf
# include ./theme.conf
font_family             Myna Nerd Font
# font_family               JetBrainsMono Nerd Font Mono Bold
# font_family             Fira Code

# font_family             JetbrainsMono Nerd Font Mono
# font_family             JetBrainsMono Nerd Font Medium
# bold_font               auto
# italic_font             auto
# bold_italic_font        auto

font_size               14.0
disable_ligatures       never
# font_features           FiraCode-Retina +zero

hide_window_decorations yes
window_padding_width    16
background_opacity      0.90


editor                  hx
macos_quit_when_last_window_closed yes
disable_ligatures cursor

active_tab_font_style   bold

env LC_CTYPE=UTF-8

allow_remote_control yes
listen-on unix:/tmp/kitty
shell zellij
shell_integration enabled

confirm_os_window_close 1



# Maps

# tilling
# more info here https://sw.kovidgoyal.net/kitty/layouts/

# include ~/.cache/wal/colors-kitty.conf
include /Users/darkawower/.config/kitty/colors.conf
map super+s no_op


# BEGIN_KITTY_THEME
# Noctalia
include current-theme.conf
# END_KITTY_THEME

nvim --headless +'KittyScrollbackGenerateKittens' +'set nonumber' +'set norelativenumber' +'%print' +'quit!' 2>&1

action_alias kitty_scrollback_nvim kitten ~/.local/share/nvim/lazy/kitty-scrollback.nvim/python/kitty_scrollback_nvim.py
mouse_map kitty_mod+right press ungrabbed combine : mouse_select_command_output : kitty_scrollback_nvim --config ksb_builtin_last_visited_cmd_output
