# Кастомная тема для Helix
# Основана на Catppuccin Frappe с прозрачным фоном (как в NeoVim)
inherits = "catppuccin_frappe"

# Прозрачный фон (адаптировано из NeoVim: transparent_background = true)
"ui.background" = {}
"ui.background.separator" = "overlay0"

# Статусная строка (стиль как в lualine)
"ui.statusline" = { fg = "subtext1", bg = "mantle" }
"ui.statusline.inactive" = { fg = "surface2", bg = "mantle" }
"ui.statusline.normal" = { fg = "base", bg = "lavender" }
"ui.statusline.insert" = { fg = "base", bg = "peach" }
"ui.statusline.select" = { fg = "base", bg = "flamingo" }

# Курсор и выделение
"ui.cursor" = { fg = "base", bg = "rosewater" }
"ui.cursor.insert" = { fg = "base", bg = "flamingo" }
"ui.cursor.select" = { fg = "base", bg = "rosewater" }
"ui.cursor.match" = { fg = "lavender", bg = "surface1" }
"ui.selection" = { bg = "surface1" }

# Номера строк (relative как в NeoVim)
"ui.linenr" = "surface1"
"ui.linenr.selected" = "lavender"

# Комментарии (цвет как в NeoVim: #42464e)
"comment" = "overlay1"

# Диагностика и ошибки
"diagnostic.hint" = { fg = "teal", modifiers = ["underlined"] }
"diagnostic.info" = { fg = "sky", modifiers = ["underlined"] }
"diagnostic.warning" = { fg = "yellow", modifiers = ["underlined"] }
"diagnostic.error" = { fg = "red", modifiers = ["underlined"] }

# Git diff (аналог gitsigns)
"diff.plus" = "green"
"diff.delta" = "yellow"
"diff.minus" = "red"

# Всплывающие окна и меню
"ui.menu" = { fg = "overlay2", bg = "surface0" }
"ui.menu.selected" = { fg = "text", bg = "surface1", modifiers = ["bold"] }
"ui.popup" = { bg = "surface0" }
"ui.popup.info" = { bg = "surface0" }

# Направляющие отступов
"ui.virtual.indent-guide" = "surface0"
"ui.virtual.whitespace" = "overlay1"

